ADR 022: GQL compliant notifications
neo4j/neo4j-python-driver pull request #1060
Opened 2024-05-23 19:05 UTC by robsdedude

2024-06-14 10:05 UTC, bigmontz requested changes
the version is wrong and there are some leftovers

2024-06-14 10:05 UTC, bigmontz commented on docs/source/api.rst
> +.. versionadded:: 5.21
```suggestion
.. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on docs/source/api.rst
> +.. versionadded:: 5.21
```suggestion
.. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on docs/source/api.rst
> +    .. versionchanged:: 5.21
```suggestion
    .. versionchanged:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_api.py
> +    .. versionadded:: 5.21
```suggestion
    .. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_api.py
> +    .. versionadded:: 5.21
```suggestion
    .. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_meta.py
> +    # print("=" * 80 + "\n")
```suggestion
```

Leftover?

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/gql_status.py
> +    .. versionadded:: 5.21
```suggestion
    .. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/gql_status.py
> +    .. versionadded:: 5.21
```suggestion
    .. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +        .. versionadded:: 5.21
```suggestion
        .. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +        #     return self._gql_status_objects
```suggestion
```

Leftover?

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +        ])
```suggestion
```

Debug leftover?

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +    .. versionadded:: 5.21
```suggestion
    .. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +# .. versionchanged:: 5.21
```suggestion
# .. versionchanged:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +    .. versionadded:: 5.21
```suggestion
    .. versionadded:: 5.22
```

2024-06-14 10:05 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +    def diagnostic_record(self) -> t.Dict[str, t.Any]:
Do we a have easy way of getting a string repr of this?

2024-06-14 10:05 UTC, bigmontz commented on testkitbackend/_async/requests.py
> +            (neo4j.PreviewWarning, r"Mutual TLS is a preview feature\.")
what does r means?

2024-06-14 10:07 UTC, robsdedude commented on testkitbackend/_async/requests.py
> +            (neo4j.PreviewWarning, r"Mutual TLS is a preview feature\.")
`r""` strings are raw strings. This means that the `\` should not be treated as an escape character but simply as a backslash.

2024-06-14 10:33 UTC, robsdedude commented on src/neo4j/_work/summary.py
> +    def diagnostic_record(self) -> t.Dict[str, t.Any]:
Yes we do. Just throw it into the `str` method (or `print` which does this implicitly).

```python
example_diag_record = {
    "null": None,
    "bool": True,
    "int": 42,
    "float": 3.14,
    "str": "Hello, World!",
    "list": [1, "abc", None],
    "dict": {"key": "value"},
    "point": neo4j.spatial.CartesianPoint((1.1, 2.3, 0.9)),
    "datetime": neo4j.time.DateTime.now(),
    "node": some_node,
    "relationship": some_rel,
}
print("Example diagnostic record:", example_diag_record)
```
will leave you with a lovely
```
Example diagnostic record: {'null': None, 'bool': True, 'int': 42, 'float': 3.14, 'str': 'Hello, World!', 'list': [1, 'abc', None], 'dict': {'key': 'value'}, 'point': POINT(1.1 2.3 0.9), 'datetime': neo4j.time.DateTime(2024, 6, 14, 11, 32, 25, 226660651), 'node': <Node element_id='4:2bcc24d0-d5ef-4540-b0f1-17e0f5d99fb0:0' labels=frozenset({'Foo'}) properties={'hello': 'world'}>, 'relationship': <Relationship element_id='5:2bcc24d0-d5ef-4540-b0f1-17e0f5d99fb0:0' nodes=(<Node element_id='4:2bcc24d0-d5ef-4540-b0f1-17e0f5d99fb0:0' labels=frozenset({'Foo'}) properties={'hello': 'world'}>, <Node element_id='4:2bcc24d0-d5ef-4540-b0f1-17e0f5d99fb0:1' labels=frozenset() properties={}>) type='BAZ' properties={'sice': 1999}>}
```

2024-06-14 10:56 UTC, bigmontz approved these changes
🛎️

2024-06-24 12:32 UTC, akollegger commented
Does GQL require an api with "GQL" in all the names?

2024-06-25 11:33 UTC, merged