Routing driver forgets addresses on some errors
neo4j/neo4j-python-driver pull request #176
Opened 2017-07-20 22:34 UTC by lutovich

This PR makes routing driver forget addresses and purge their connections on network and database errors. It also makes driver forget write server addresses when they fail as writers, connections remain in the pool because such machines can remain readers/routers.

2017-07-26 11:47 UTC, zhenlineo commented
LGTM. CC @technige

2017-07-28 08:52 UTC, technige requested changes
Not keen on the `error_handler` changes to `connection.py`. It's quite unusual to dynamically attach methods in this way and the new `try...except` blocks catch all `Exception` types, which is generally considered too brute force.

I'm happy to pair on this.

2017-08-04 17:00 UTC, lutovich commented
@technige dynamic `error_handler` is now replaced by constructor injection of `ConnectionErrorHandler`. Later is different for direct and routing driver.

2017-08-22 13:27 UTC, technige approved these changes

2017-08-23 14:13 UTC, merged