Notifications api
neo4j/neo4j-python-driver pull request #847
Opened 2022-10-28 12:33 UTC by robsdedude

2022-10-28 12:36 UTC, robsdedude commented on CHANGELOG.md
> +## Version 5.x
:warning: Before merging: don't forget to finalize!

2022-10-28 12:36 UTC, robsdedude commented on docs/source/api.rst
> +.. versionadded:: 5.2
:warning: Before merging: don't forget to finalize!

2022-10-28 12:36 UTC, robsdedude commented on docs/source/api.rst
> +.. versionadded:: 5.2
:warning: Before merging: don't forget to finalize!

2022-10-28 12:36 UTC, robsdedude commented on neo4j/_api.py
> +    .. versionadded:: 5.2
:warning: Before merging: don't forget to finalize!

2022-10-28 12:36 UTC, robsdedude commented on neo4j/_api.py
> +    .. versionadded:: 5.2
:warning: Before merging: don't forget to finalize!

2022-10-28 12:36 UTC, robsdedude commented on neo4j/_api.py
> +    .. versionadded:: 5.2
:warning: Before merging: don't forget to finalize!

2022-10-28 12:45 UTC, robsdedude commented on tests/unit/common/work/test_summary.py
> +
```suggestion
```

2023-03-20 10:01 UTC, bigmontz requested changes
The behaviour of the property `category` of the ResultSummary is wrong, it should be `UNKNOWN` when the category is not present in the metadata.

2023-03-20 10:01 UTC, bigmontz commented on bin/make-unasync
> +        "AsyncMock": "MagicMock",
Where did MagicMock come from?

2023-03-20 10:01 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +            )
You are overriding category with a value which come direct from the wire. This value should be UNKNOWN by default like `severity_level`.

2023-03-20 10:40 UTC, bigmontz commented on src/neo4j/_work/summary.py
> +            )
The code was missread.

2023-03-20 10:41 UTC, bigmontz approved these changes
🔢

2023-03-20 10:45 UTC, robsdedude commented on bin/make-unasync
> +        "AsyncMock": "MagicMock",
the mocking library has `Mock` and `MagicMock` which behave the same except that the latter also mock magic methods (`__xyz__` shaped methods). `AsyncMock` does always mock magic methods as well (I suppose it has to, to be able to intercept calls to `__await__`, but that is speculation). Either way, by default the unasync script would turn `AsyncMock` into `Mock` which brakes tests that rely on magic methods being mocked.

2023-03-20 17:15 UTC, merged