General API docs improvements
neo4j/neo4j-python-driver pull request #858
Opened 2022-11-18 11:34 UTC by robsdedude

Including
 * more details
 * better examples
 * code formatting
 * more consistent docstring format

2022-11-21 15:29 UTC, stefano-ottolenghi requested changes

2022-11-21 15:29 UTC, stefano-ottolenghi commented on neo4j/_async/work/result.py
> +        have to implement a custom serialzer should you need more control over
typo in `serializer`

2022-11-21 15:30 UTC, stefano-ottolenghi commented
Other than the typo, LGTM! 🦆

2022-11-21 16:06 UTC, robsdedude commented on neo4j/_async/work/result.py
> +        have to implement a custom serialzer should you need more control over
fixed

2022-11-22 07:40 UTC, stefano-ottolenghi approved these changes

2022-11-22 15:01 UTC, AndyHeap-NeoTech approved these changes
All looks sensible and good to me. Approved.

2022-11-22 15:32 UTC, merged