Updated examples and docs
neo4j/neo4j-python-driver pull request #929
Opened 2023-05-17 14:37 UTC by robsdedude

* Remove 3.5->4.x migration notes
 * Update examples to use `driver.execute_query` where appropriate
 * Updated links to external resources

2023-05-22 14:03 UTC, fbiville requested changes

2023-05-22 14:03 UTC, fbiville commented on README.rst
> +            "MERGE (a)-[:KNOWS]->(friend:Person {name: $friend_name})",
maybe out of scope, but a better example would likely be:
```cypher
            "MERGE (a:Person {name: $name}) "
            "MERGE (friend:Person {name: $friend_name}) "
            "MERGE (a)-[:KNOWS]->(friend)"
```

2023-05-22 14:03 UTC, fbiville commented on README.rst
> +            "MERGE (a)-[:KNOWS]->(friend:Person {name: $friend_name})",
the current impl would create duplicate friends if the KNOWS rel is missing which is rarely what you want to do

2023-05-22 14:03 UTC, fbiville commented on README.rst
> +Further Information
maybe add GraphAcademy as well?

2023-05-22 14:03 UTC, fbiville commented on docs/source/index.rst
> +            "MERGE (a)-[:KNOWS]->(friend:Person {name: $friend_name})",
same as previous comment

2023-05-22 14:03 UTC, fbiville commented on docs/source/index.rst
> +Further Information
same as above

2023-05-22 14:03 UTC, fbiville commented on src/neo4j/_async/auth_management.py
> +            The provider must function only ever return auth information
typo?

2023-05-22 14:03 UTC, fbiville commented on src/neo4j/_sync/auth_management.py
> +            The provider must function only ever return auth information
typo?

2023-05-22 14:03 UTC, fbiville commented on tests/integration/test_readme.py
> +            "MERGE (a:Person {name: $name}) "
same as before

2023-05-25 15:52 UTC, fbiville approved these changes

2023-05-25 15:53 UTC, AndyHeap-NeoTech approved these changes
All good.

2023-05-29 07:45 UTC, merged